blank_issues_enabled: true
contact_links:
  - name: VCC repository URL
    url: https://yani-cloud7.github.io/vrchat-error-whisperer/index.json
    about: Add this URL in VRChat Creator Companion to install the alpha package.

